# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: "J8X43LDDQC",
      issuer_id: "163f3302-fdb7-49f8-ba18-9cf7c569b4cf",
      key_filepath: "./fastlane/key/AuthKey_J8X43LDDQC.p8",
      duration: 1200,
      in_house: false,
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    match(type: "appstore", git_url: "https://github.com/CovenantNomad/KnockKnock-Certification.git")
    build_app(workspace: "knockknock.xcworkspace", scheme: "knockknock", configuration: "Release")
    upload_to_app_store(
      submit_for_review: false,
      overwrite_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false,
    )
  end
end
